// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhiloAlterEgo.DAL.Data;

#nullable disable

namespace PhiloAlterEgo.DAL.Migrations.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220709155519_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GuildKingdom", b =>
                {
                    b.Property<decimal>("GuildsId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("KingdomsId")
                        .HasColumnType("int");

                    b.HasKey("GuildsId", "KingdomsId");

                    b.HasIndex("KingdomsId");

                    b.ToTable("GuildKingdom");
                });

            modelBuilder.Entity("PhiloAlterEgo.DAL.Models.Governor", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.ToTable("Governors");
                });

            modelBuilder.Entity("PhiloAlterEgo.DAL.Models.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPermission")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("PhiloAlterEgo.DAL.Models.Kingdom", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kingdoms");
                });

            modelBuilder.Entity("PhiloAlterEgo.DAL.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Dead")
                        .HasColumnType("int");

                    b.Property<decimal>("GovernorId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("ResourcesGathered")
                        .HasColumnType("int");

                    b.Property<int>("ResourcesShared")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScannedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("T4Kills")
                        .HasColumnType("int");

                    b.Property<int>("T5Kills")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GovernorId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("GuildKingdom", b =>
                {
                    b.HasOne("PhiloAlterEgo.DAL.Models.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhiloAlterEgo.DAL.Models.Kingdom", null)
                        .WithMany()
                        .HasForeignKey("KingdomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhiloAlterEgo.DAL.Models.Governor", b =>
                {
                    b.HasOne("PhiloAlterEgo.DAL.Models.Kingdom", "Kingdom")
                        .WithMany("Governors")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("PhiloAlterEgo.DAL.Models.Stats", b =>
                {
                    b.HasOne("PhiloAlterEgo.DAL.Models.Governor", "Governor")
                        .WithMany("Stats")
                        .HasForeignKey("GovernorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governor");
                });

            modelBuilder.Entity("PhiloAlterEgo.DAL.Models.Governor", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("PhiloAlterEgo.DAL.Models.Kingdom", b =>
                {
                    b.Navigation("Governors");
                });
#pragma warning restore 612, 618
        }
    }
}
